### ISSUE TITLE
Specify log severity?

### ISSUE THREAD

**Issue by chrisst** [nickmarrone/httperrors#1]
I realized that in addition to inferring the statusCode right now we are also inferring the log severity based on status code. Which means that some things like timeouts end up being logged as warnings. However when checking account limits, a timeout should really be an error, whereas timeouts to other things might actually be warnings.

**Comment by nickmarrone** [comment]
@ThorArakis, for real errors and warnings, it might make more sense to log them at the source, and then log all error responses at the informational level prior to response.

**Comment by chrisst** [comment]
Yeah that makes sense. It seems with that strategy we would probably just log all errors getting returned to the user in the generic handler as a warning? It would mean that real errors would get double logged but at least we'd have a safety net to catch anything where we missed the logging. Thoughts?

**Comment by nickmarrone** [comment]
I was thinking just logging all errors getting responded to by the user as INFO (actually, logging anything that is not a GET), and logging real errors (for instance, failure to read from external service) at point of error. I was thinking about this yesterday when the reports team was looking for logs on a create and I didn't have anything to give them other than the debug logs we added.

**Comment by chrisst** [comment]
I do like the idea of logging the error at the point where it occurred. But I would probably lean towards logging each request entry as INFO and any user facing errors as WARN. That way we can search for all non-caught errors without needing to filter out all the other noise in INFO and DEBUG. 

In regards to the reports team. What kind of info were they looking for?

**Comment by nickmarrone** [comment]
I can get behind that. They wanted to see why creation failed. As far as I could tell, we did not log it -- at least not in an easily locatable way. 

EDIT: Double logging is the least of our worries here. If we are logging ERR level we can easily filter for service problems.

**Comment by chrisst** [comment]
I wasn't able to find the creation problems at first, and then realized we were logging many of them as WARN's already =P

**Comment by chrisst** [comment]
http://kibana.prod.chi.intsm.net/#/discover?_g=(refreshInterval:(display:Off,section:0,value:0),time:(from:'2016-04-14T20:07:29.594Z',mode:absolute,to:'2016-04-14T20:12:13.378Z'))&_a=(columns:!(message),index:%5Blogstash-%5DYYYY.MM.DD,interval:auto,query:(query_string:(analyze_wildcard:!t,query:'syslog_program:%22data-sources%22%20AND%20env:%22prod-chi%22%20AND%20syslog_severity:warning')),sort:!('@timestamp',desc))
